packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  postcss: '>=8.5.23'
  mysql2: '>=3.23.1'
  deepmerge-ts: '>=8.0.0'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  argon2: true
  esbuild: false
  msgpackr-extract: true
  prisma: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - eslint@10.10.0
